import { Show } from 'solid-js';
import {
  store,
  reorderTask,
  setActiveTask,
  updateTaskName,
  collapseTask,
  getTaskDotStatus,
  getTaskAttentionState,
  toggleTaskFocusMode,
  clearTaskLandingReview,
  getPrChecks,
  getVerifyCommand,
  isTaskCanvasVisible,
  openTaskCanvas,
  closeTaskCanvas,
} from '../store/store';
import { EditableText, type EditableTextHandle } from './EditableText';
import { IconButton } from './IconButton';
import { StatusDot, getDotTooltip } from './StatusDot';
import {
  CheckIcon,
  CloseIcon,
  CollapseIcon,
  ExpandIcon,
  MinusIcon,
  PanelRightIcon,
  PullRequestIcon,
  PushIcon,
} from './icons';
import { theme } from '../lib/theme';
import { badgeStyle } from '../lib/badgeStyle';
import {
  summarizeVerificationRun,
  usesVerificationRun,
  type VerificationSummaryKind,
} from '../lib/verification-run';
import { handleDragReorder } from '../lib/dragReorder';
import { getTaskDockerBadgeLabel } from '../lib/docker';
import { displayTaskNameFromPrompt, shouldUsePromptDerivedTaskName } from '../lib/clean-task-name';
import type { Task } from '../store/types';
import { isLandedTaskState } from '../store/landing';

// Kinds without an entry stay silent: a configured-but-never-run command on
// every task would be noise, and cancelled runs carry no signal.
const RUN_BADGES: Partial<Record<VerificationSummaryKind, { label: string; color: string }>> = {
  running: { label: 'Verifying…', color: theme.fgMuted },
  passed: { label: 'Verified', color: theme.success },
  stale: { label: 'Verify stale', color: theme.warning },
  dirty: { label: 'Verified (dirty)', color: theme.warning },
  failed: { label: 'Verify failed', color: theme.error },
};

interface TaskTitleBarProps {
  task: Task;
  isActive: boolean;
  onClose: () => void;
  onMerge: () => void;
  onPush: () => void;
  pushing: boolean;
  pushSuccess: boolean;
  onTitleEditRef: (h: EditableTextHandle) => void;
}

export function TaskTitleBar(props: TaskTitleBarProps) {
  const dockerBadgeLabel = () => getTaskDockerBadgeLabel(props.task.dockerSource);
  const isLandedTask = () => isLandedTaskState(props.task.landingState);
  const landingBadge = () => {
    switch (props.task.landingState) {
      case 'landed_pending_review':
        return { label: 'Landed', color: theme.success, title: 'Landed — pending review' };
      case 'landed_cleanup_failed':
        return {
          label: 'Cleanup failed',
          color: theme.warning,
          title: props.task.landingReason ?? 'Landed, but cleanup failed',
        };
      case 'landing_escalated':
        return {
          label: 'Landing blocked',
          color: theme.warning,
          title: props.task.landingReason ?? 'Landing needs attention',
        };
      case 'landing_failed':
        return {
          label: 'Landing failed',
          color: theme.error,
          title: props.task.landingReason ?? 'Landing failed',
        };
      case 'reviewed':
        return { label: 'Reviewed', color: theme.fgMuted, title: 'Landing reviewed' };
      default:
        return null;
    }
  };
  // Same precedence as the merge dialog so the badge and its readiness row agree.
  const verificationBadge = () =>
    usesVerificationRun(props.task.verificationRun, Boolean(getVerifyCommand(props.task.id)))
      ? runVerificationBadge()
      : reportedVerificationBadge();
  const runVerificationBadge = () => {
    const summary = summarizeVerificationRun(
      props.task.verificationRun,
      store.taskGitStatus[props.task.id]?.head_sha,
    );
    const badge = RUN_BADGES[summary.kind];
    return badge ? { ...badge, title: `${summary.label}. ${summary.detail}` } : null;
  };
  const reportedVerificationBadge = () => {
    const checks = props.task.verification?.checks;
    if (!checks?.length) return null;
    if (checks.every((check) => check.result === 'passed')) {
      return {
        label: `Verified ${checks.length}`,
        color: theme.success,
        title: checks.map((check) => `${check.name}: ${check.command}`).join('\n'),
      };
    }
    const failed = checks.find((check) => check.result !== 'passed');
    return {
      label: failed?.result === 'blocked' ? 'Verification blocked' : 'Verification failed',
      color: theme.warning,
      title: failed
        ? `${failed.name}: ${failed.command}${failed.reason ? `\n${failed.reason}` : ''}`
        : 'Verification did not pass',
    };
  };
  const titleLabel = () => {
    const initialPrompt = props.task.savedInitialPrompt?.trim();
    if (
      !initialPrompt ||
      !shouldUsePromptDerivedTaskName(
        props.task.name,
        initialPrompt,
        props.task.nameIsAutoGenerated,
      )
    ) {
      return props.task.name;
    }
    return displayTaskNameFromPrompt(initialPrompt) || props.task.name;
  };
  const ciChecks = () => {
    const c = getPrChecks(props.task.id);
    return c && c.overall !== 'none' ? c : null;
  };
  const ciTitle = (): string => {
    const c = ciChecks();
    if (!c) return '';
    if (c.overall === 'pending') {
      return `CI running — ${c.pending} pending, ${c.passing} passing${c.failing ? `, ${c.failing} failing` : ''}`;
    }
    if (c.overall === 'success') {
      return `CI passed — ${c.passing} check${c.passing === 1 ? '' : 's'}`;
    }
    return `CI failed — ${c.failing} failing, ${c.passing} passing${c.pending ? `, ${c.pending} pending` : ''}`;
  };
  const pushTitle = () => {
    const ci = ciTitle();
    return ci ? `Push to remote\n${ci}` : 'Push to remote';
  };

  function handleTitleMouseDown(e: MouseEvent) {
    handleDragReorder(e, {
      itemId: props.task.id,
      getTaskOrder: () => store.taskOrder,
      onReorder: reorderTask,
      onTap: () => setActiveTask(props.task.id),
    });
  }

  return (
    <div class="task-title-bar" data-active={props.isActive} onMouseDown={handleTitleMouseDown}>
      <EditableText
        value={titleLabel()}
        onCommit={(v) => updateTaskName(props.task.id, v)}
        class="editable-text"
        title={props.task.savedInitialPrompt}
        ref={(h) => props.onTitleEditRef(h)}
      />
      <div class="task-title-details">
        <span class="task-title-status">
          <StatusDot
            status={getTaskDotStatus(props.task.id)}
            size="md"
            attention={getTaskAttentionState(props.task.id)}
          />
          <span>
            {getDotTooltip(getTaskDotStatus(props.task.id), getTaskAttentionState(props.task.id))}
          </span>
        </span>
        <Show when={props.task.gitIsolation === 'direct'}>
          <span style={badgeStyle(theme.warning)}>{props.task.branchName}</span>
        </Show>
        <Show when={props.task.gitIsolation === 'none'}>
          <span style={badgeStyle(theme.fgMuted)}>no git</span>
        </Show>
        <Show when={props.task.dockerMode}>
          <span style={badgeStyle(theme.fgMuted)} title={props.task.dockerImage}>
            {dockerBadgeLabel()}
          </span>
        </Show>
        <Show when={props.task.externalWorktree}>
          <span style={badgeStyle(theme.accent)}>Imported</span>
        </Show>
        <Show when={props.task.needsReview}>
          <span
            style={badgeStyle(theme.warning)}
            title={props.task.landingReason ?? 'Review this task'}
          >
            Review
          </span>
        </Show>
        <Show when={landingBadge()}>
          {(badge) => (
            <button
              style={{
                ...badgeStyle(badge().color),
                cursor: props.task.landingState === 'landed_pending_review' ? 'pointer' : 'default',
              }}
              title={
                props.task.landingState === 'landed_pending_review'
                  ? `${badge().title}. Click to mark reviewed.`
                  : badge().title
              }
              onClick={(e) => {
                e.stopPropagation();
                if (props.task.landingState === 'landed_pending_review') {
                  clearTaskLandingReview(props.task.id);
                }
              }}
            >
              {badge().label}
            </button>
          )}
        </Show>
        <Show when={verificationBadge()}>
          {(badge) => (
            <span style={badgeStyle(badge().color)} title={badge().title}>
              {badge().label}
            </span>
          )}
        </Show>
      </div>
      <div class="task-title-actions">
        <Show when={props.task.gitIsolation === 'worktree' && !isLandedTask()}>
          <IconButton
            icon={<PullRequestIcon />}
            onClick={() => props.onMerge()}
            title={props.task.baseBranch ? `Merge into ${props.task.baseBranch}` : 'Merge'}
          />
          <div style={{ position: 'relative', display: 'inline-flex' }}>
            <Show
              when={!props.pushing}
              fallback={
                <div
                  style={{
                    display: 'inline-flex',
                    'align-items': 'center',
                    'justify-content': 'center',
                    padding: '4px',
                    border: `1px solid ${theme.border}`,
                    'border-radius': 'var(--radius-sm)',
                  }}
                >
                  <span class="inline-spinner" style={{ width: '14px', height: '14px' }} />
                </div>
              }
            >
              <IconButton icon={<PushIcon />} onClick={() => props.onPush()} title={pushTitle()} />
            </Show>
            <Show
              when={ciChecks()}
              fallback={
                <Show when={props.pushSuccess}>
                  <div
                    style={{
                      position: 'absolute',
                      bottom: '-4px',
                      right: '-4px',
                      width: '12px',
                      height: '12px',
                      'border-radius': '50%',
                      background: theme.success,
                      display: 'flex',
                      'align-items': 'center',
                      'justify-content': 'center',
                      'pointer-events': 'none',
                    }}
                  >
                    <CheckIcon size={8} style={{ color: '#ffffff' }} />
                  </div>
                </Show>
              }
            >
              {(c) => (
                <div
                  style={{
                    position: 'absolute',
                    bottom: '-4px',
                    right: '-4px',
                    width: '14px',
                    height: '14px',
                    'border-radius': '50%',
                    background:
                      c().overall === 'pending'
                        ? 'transparent'
                        : c().overall === 'success'
                          ? theme.success
                          : theme.error,
                    display: 'flex',
                    'align-items': 'center',
                    'justify-content': 'center',
                    color: c().overall === 'pending' ? theme.warning : 'white',
                    'pointer-events': 'none',
                  }}
                >
                  <Show when={c().overall === 'pending'}>
                    <span class="inline-spinner" style={{ width: '12px', height: '12px' }} />
                  </Show>
                  <Show when={c().overall === 'success'}>
                    <CheckIcon size={9} />
                  </Show>
                  <Show when={c().overall === 'failure'}>
                    <CloseIcon size={9} />
                  </Show>
                </div>
              )}
            </Show>
          </div>
        </Show>
        <IconButton
          icon={
            <PanelRightIcon
              style={{ color: isTaskCanvasVisible(props.task) ? theme.accent : undefined }}
            />
          }
          onClick={() =>
            isTaskCanvasVisible(props.task)
              ? closeTaskCanvas(props.task.id)
              : openTaskCanvas(props.task.id)
          }
          title={isTaskCanvasVisible(props.task) ? 'Close canvas' : 'Open canvas'}
        />
        <IconButton
          icon={store.focusMode ? <ExpandIcon /> : <CollapseIcon />}
          onClick={() => {
            toggleTaskFocusMode(props.task.id);
          }}
          title={store.focusMode ? 'Exit focus mode' : 'Focus on this task'}
        />
        <Show when={!props.task.coordinatorMode}>
          <IconButton
            icon={<MinusIcon />}
            onClick={() => collapseTask(props.task.id)}
            title="Collapse task"
          />
        </Show>
        <IconButton icon={<CloseIcon />} onClick={() => props.onClose()} title="Close task" />
      </div>
    </div>
  );
}
