import { Show } from 'solid-js';
import {
  store,
  reorderTask,
  activateTaskFromPointer,
  updateTaskName,
  collapseTask,
  getTaskDotStatus,
  getTaskAttentionState,
  toggleTaskFocusMode,
  clearTaskLandingReview,
  getPrChecks,
  getVerifyCommand,
  getEvidenceConfidence,
  isTaskCanvasVisible,
  openTaskCanvas,
  closeTaskCanvas,
} from '../store/store';
import { EditableText, type EditableTextHandle } from './EditableText';
import { IconButton } from './IconButton';
import { StatusDot, getDotTooltip } from './StatusDot';
import { CheckIcon, CloseIcon } from './icons';
import { theme } from '../lib/theme';
import { badgeStyle } from '../lib/badgeStyle';
import { taskCheckSignal } from '../lib/task-check-signal';
import { handleDragReorder } from '../lib/dragReorder';
import { getTaskDockerBadgeLabel } from '../lib/docker';
import { displayTaskNameFromPrompt, shouldUsePromptDerivedTaskName } from '../lib/clean-task-name';
import type { Task } from '../store/types';
import { isLandedTaskState } from '../store/landing';
import { bringTaskToFront, isTaskBackgrounded, sendTaskToBack } from '../store/background-tasks';

interface TaskTitleBarProps {
  task: Task;
  isActive: boolean;
  onClose: () => void;
  /** Opens the finish dialog: evidence, tour, then merge or push. */
  onFinish: () => void;
  pushing: boolean;
  pushSuccess: boolean;
  onTitleEditRef: (h: EditableTextHandle) => void;
}

export function TaskTitleBar(props: TaskTitleBarProps) {
  const dockerBadgeLabel = () => getTaskDockerBadgeLabel(props.task.dockerSource);
  const isLandedTask = () => isLandedTaskState(props.task.landingState);
  const landingBadge = () => {
    switch (props.task.landingState) {
      case 'landed_pending_review':
        return { label: 'Landed', color: theme.success, title: 'Landed — pending review' };
      case 'landed_cleanup_failed':
        return {
          label: 'Cleanup failed',
          color: theme.warning,
          title: props.task.landingReason ?? 'Landed, but cleanup failed',
        };
      case 'landing_escalated':
        return {
          label: 'Landing blocked',
          color: theme.warning,
          title: props.task.landingReason ?? 'Landing needs attention',
        };
      case 'landing_failed':
        return {
          label: 'Landing failed',
          color: theme.error,
          title: props.task.landingReason ?? 'Landing failed',
        };
      case 'reviewed':
        return { label: 'Reviewed', color: theme.fgMuted, title: 'Landing reviewed' };
      default:
        return null;
    }
  };
  // Hidden while the agent works: the result is about to change anyway. A busy
  // shell (dev server, watcher) is not agent work and must not hide a failure.
  const checkSignal = () => {
    const attention = getTaskAttentionState(props.task.id);
    if (attention === 'active' || (!attention && getTaskDotStatus(props.task.id) === 'busy'))
      return undefined;
    const git = store.taskGitStatus[props.task.id];
    return taskCheckSignal({
      evidence: getEvidenceConfidence(props.task, git),
      evidencePackage: props.task.evidence,
      verificationRun: props.task.verificationRun,
      verification: props.task.verification,
      verifyCommandConfigured: Boolean(getVerifyCommand(props.task.id)),
      headSha: git?.head_sha,
    });
  };
  const titleLabel = () => {
    const initialPrompt = props.task.savedInitialPrompt?.trim();
    if (
      !initialPrompt ||
      !shouldUsePromptDerivedTaskName(
        props.task.name,
        initialPrompt,
        props.task.nameIsAutoGenerated,
      )
    ) {
      return props.task.name;
    }
    return displayTaskNameFromPrompt(initialPrompt) || props.task.name;
  };
  const ciChecks = () => {
    const c = getPrChecks(props.task.id);
    return c && c.overall !== 'none' ? c : null;
  };
  const ciTitle = (): string => {
    const c = ciChecks();
    if (!c) return '';
    if (c.overall === 'pending') {
      return `CI running — ${c.pending} pending, ${c.passing} passing${c.failing ? `, ${c.failing} failing` : ''}`;
    }
    if (c.overall === 'success') {
      return `CI passed — ${c.passing} check${c.passing === 1 ? '' : 's'}`;
    }
    return `CI failed — ${c.failing} failing, ${c.passing} passing${c.pending ? `, ${c.pending} pending` : ''}`;
  };
  const finishTitle = () => {
    const base = props.task.baseBranch ?? 'base';
    const title = props.pushing
      ? 'Pushing… (open to see output)'
      : `Finish: merge into ${base} or push`;
    const ci = ciTitle();
    return ci ? `${title}\n${ci}` : title;
  };

  const statusDescription = () =>
    getDotTooltip(getTaskDotStatus(props.task.id), getTaskAttentionState(props.task.id));

  function handleTitleMouseDown(e: MouseEvent) {
    handleDragReorder(e, {
      itemId: props.task.id,
      getTaskOrder: () => store.taskOrder,
      onReorder: reorderTask,
      onTap: () => activateTaskFromPointer(props.task.id),
    });
  }

  return (
    <div class="task-title-bar" data-active={props.isActive} onMouseDown={handleTitleMouseDown}>
      <EditableText
        value={titleLabel()}
        onCommit={(v) => updateTaskName(props.task.id, v)}
        class="editable-text"
        title={props.task.savedInitialPrompt || titleLabel()}
        ref={(h) => props.onTitleEditRef(h)}
      />
      <div class="task-title-details">
        <span class="task-title-status" title={statusDescription()}>
          <StatusDot
            status={getTaskDotStatus(props.task.id)}
            taskId={props.task.id}
            size="md"
            attention={getTaskAttentionState(props.task.id)}
          />
          <span>
            <span>{statusDescription().split(' — ')[0]}</span>
            <span class="task-status-explanation">
              {statusDescription().includes(' — ')
                ? ` — ${statusDescription().split(' — ').slice(1).join(' — ')}`
                : ''}
            </span>
            <Show when={checkSignal()}>
              {(signal) => (
                <span style={{ color: signal().color }} title={signal().title}>
                  {` · ${signal().label}`}
                </span>
              )}
            </Show>
          </span>
        </span>
        <Show when={props.task.gitIsolation === 'direct'}>
          <span style={badgeStyle(theme.warning)}>{props.task.branchName}</span>
        </Show>
        <Show when={props.task.gitIsolation === 'none'}>
          <span style={badgeStyle(theme.fgMuted)}>no git</span>
        </Show>
        <Show when={props.task.dockerMode}>
          <span style={badgeStyle(theme.fgMuted)} title={props.task.dockerImage}>
            {dockerBadgeLabel()}
          </span>
        </Show>
        <Show when={props.task.externalWorktree}>
          <span style={badgeStyle(theme.accent)}>Imported</span>
        </Show>
        <Show when={isTaskBackgrounded(props.task.id)}>
          <span style={badgeStyle(theme.fgMuted)}>Background</span>
        </Show>
        <Show when={props.task.needsReview}>
          <span
            style={badgeStyle(theme.warning)}
            title={props.task.landingReason ?? 'Review this task'}
          >
            Review
          </span>
        </Show>
        <Show when={landingBadge()}>
          {(badge) => (
            <button
              style={{
                ...badgeStyle(badge().color),
                cursor: props.task.landingState === 'landed_pending_review' ? 'pointer' : 'default',
              }}
              title={
                props.task.landingState === 'landed_pending_review'
                  ? `${badge().title}. Click to mark reviewed.`
                  : badge().title
              }
              onClick={(e) => {
                e.stopPropagation();
                if (props.task.landingState === 'landed_pending_review') {
                  clearTaskLandingReview(props.task.id);
                }
              }}
            >
              {badge().label}
            </button>
          )}
        </Show>
      </div>
      <div class="task-title-actions">
        <Show when={props.task.gitIsolation === 'worktree' && !isLandedTask()}>
          <div class="task-action-group" role="group" aria-label="Git actions">
            <div style={{ position: 'relative', display: 'inline-flex' }}>
              <IconButton
                icon={
                  <Show
                    when={!props.pushing}
                    fallback={
                      <span class="inline-spinner" style={{ width: '14px', height: '14px' }} />
                    }
                  >
                    <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor">
                      <path d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8Zm1.5 0a6.5 6.5 0 1 0 13 0 6.5 6.5 0 0 0-13 0Zm10.28-1.72-4.5 4.5a.75.75 0 0 1-1.06 0l-2-2a.75.75 0 0 1 1.06-1.06L6.75 9.19l3.97-3.97a.75.75 0 0 1 1.06 1.06Z" />
                    </svg>
                  </Show>
                }
                onClick={() => props.onFinish()}
                title={finishTitle()}
              />
              <Show
                when={ciChecks()}
                fallback={
                  <Show when={props.pushSuccess}>
                    <div
                      class="task-git-status-badge"
                      style={{
                        position: 'absolute',
                        bottom: '-4px',
                        right: '-4px',
                        width: '12px',
                        height: '12px',
                        'border-radius': '50%',
                        background: theme.success,
                        display: 'flex',
                        'align-items': 'center',
                        'justify-content': 'center',
                        color: 'white',
                        'pointer-events': 'none',
                      }}
                    >
                      <svg width="8" height="8" viewBox="0 0 16 16" fill="currentColor">
                        <path d="M13.78 4.22a.75.75 0 0 1 0 1.06l-7.25 7.25a.75.75 0 0 1-1.06 0L2.22 9.28a.75.75 0 0 1 1.06-1.06L6 10.94l6.72-6.72a.75.75 0 0 1 1.06 0Z" />
                      </svg>
                    </div>
                  </Show>
                }
              >
                {(c) => (
                  <div
                    class="task-git-status-badge"
                    data-result={c().overall}
                    style={{
                      position: 'absolute',
                      bottom: '-4px',
                      right: '-4px',
                      width: '14px',
                      height: '14px',
                      'border-radius': '50%',
                      background:
                        c().overall === 'pending'
                          ? 'transparent'
                          : c().overall === 'success'
                            ? theme.success
                            : theme.error,
                      display: 'flex',
                      'align-items': 'center',
                      'justify-content': 'center',
                      color: c().overall === 'pending' ? theme.warning : 'white',
                      'pointer-events': 'none',
                    }}
                  >
                    <Show when={c().overall === 'pending'}>
                      <span class="inline-spinner" style={{ width: '12px', height: '12px' }} />
                    </Show>
                    <Show when={c().overall === 'success'}>
                      <CheckIcon size={9} />
                    </Show>
                    <Show when={c().overall === 'failure'}>
                      <CloseIcon size={9} />
                    </Show>
                  </div>
                )}
              </Show>
            </div>
          </div>
        </Show>
        <div class="task-action-group" role="group" aria-label="View actions">
          <IconButton
            icon={
              <svg
                width="16"
                height="16"
                viewBox="0 0 16 16"
                fill="none"
                stroke="currentColor"
                stroke-width="1.5"
                style={{ color: isTaskCanvasVisible(props.task) ? theme.accent : undefined }}
              >
                <rect x="1.75" y="2.75" width="12.5" height="10.5" rx="1.5" />
                <path d="M10 2.75v10.5" />
              </svg>
            }
            onClick={() =>
              isTaskCanvasVisible(props.task)
                ? closeTaskCanvas(props.task.id)
                : openTaskCanvas(props.task.id)
            }
            title={isTaskCanvasVisible(props.task) ? 'Close canvas' : 'Open canvas'}
          />
          <IconButton
            icon={
              store.focusMode ? (
                <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor">
                  <path d="M5.5 2.75A.75.75 0 0 0 4.75 2H2.5a.5.5 0 0 0-.5.5v2.25a.75.75 0 0 0 1.5 0V3.5h1.25a.75.75 0 0 0 .75-.75ZM11.25 2a.75.75 0 0 0 0 1.5H12.5v1.25a.75.75 0 0 0 1.5 0V2.5a.5.5 0 0 0-.5-.5h-2.25ZM3.5 11.25a.75.75 0 0 0-1.5 0V13.5a.5.5 0 0 0 .5.5h2.25a.75.75 0 0 0 0-1.5H3.5v-1.25ZM14 11.25a.75.75 0 0 0-1.5 0v1.25h-1.25a.75.75 0 0 0 0 1.5H13.5a.5.5 0 0 0 .5-.5v-2.25Z" />
                </svg>
              ) : (
                <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor">
                  <path d="M2.75 5.5A.75.75 0 0 0 3.5 4.75V3.5h1.25a.75.75 0 0 0 0-1.5H2.5a.5.5 0 0 0-.5.5v2.25c0 .414.336.75.75.75ZM12.5 4.75a.75.75 0 0 0 1.5 0V2.5a.5.5 0 0 0-.5-.5h-2.25a.75.75 0 0 0 0 1.5h1.25v1.25ZM3.5 11.25a.75.75 0 0 0-1.5 0V13.5a.5.5 0 0 0 .5.5h2.25a.75.75 0 0 0 0-1.5H3.5v-1.25ZM13.25 10.5a.75.75 0 0 0-.75.75v1.25h-1.25a.75.75 0 0 0 0 1.5H13.5a.5.5 0 0 0 .5-.5v-2.25a.75.75 0 0 0-.75-.75Z" />
                </svg>
              )
            }
            onClick={() => {
              toggleTaskFocusMode(props.task.id);
            }}
            title={store.focusMode ? 'Exit focus mode' : 'Focus on this task'}
          />
        </div>
        <div class="task-action-group" role="group" aria-label="Task actions">
          <IconButton
            icon={
              <svg
                width="16"
                height="16"
                viewBox="0 0 16 16"
                fill="none"
                stroke="currentColor"
                stroke-width="1.5"
                stroke-linecap="round"
                stroke-linejoin="round"
              >
                <path d="M3 3h10M3 13h10" />
                <path
                  d={
                    isTaskBackgrounded(props.task.id)
                      ? 'M8 11V5m0 0L5.5 7.5M8 5l2.5 2.5'
                      : 'M8 5v6m0 0L5.5 8.5M8 11l2.5-2.5'
                  }
                />
              </svg>
            }
            onClick={() =>
              isTaskBackgrounded(props.task.id)
                ? bringTaskToFront(props.task.id)
                : sendTaskToBack(props.task.id)
            }
            title={
              isTaskBackgrounded(props.task.id)
                ? 'Bring task to front'
                : 'Send task to back until new activity'
            }
          />
          <Show when={!props.task.coordinatorMode && !props.task.delegationParent}>
            <IconButton
              icon={
                <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor">
                  <path d="M2 8a.75.75 0 0 1 .75-.75h10.5a.75.75 0 0 1 0 1.5H2.75A.75.75 0 0 1 2 8Z" />
                </svg>
              }
              onClick={() => collapseTask(props.task.id)}
              title="Collapse task"
            />
          </Show>
          <IconButton icon={<CloseIcon />} onClick={() => props.onClose()} title="Close task" />
        </div>
      </div>
    </div>
  );
}
