import { Show } from 'solid-js';
import {
  store,
  reorderTask,
  activateTaskFromPointer,
  updateTaskName,
  collapseTask,
  getTaskDotStatus,
  getTaskAttentionState,
  toggleTaskFocusMode,
  clearTaskLandingReview,
  getVerifyCommand,
  getEvidenceConfidence,
  isTaskCanvasVisible,
  openTaskCanvas,
  closeTaskCanvas,
} from '../store/store';
import { EditableText, type EditableTextHandle } from './EditableText';
import { IconButton } from './IconButton';
import { MoreMenu } from './chat/MoreMenu';
import { StatusDot, getDotTooltip } from './StatusDot';
import { ActivityIcon, ClockIcon, CloseIcon, PlayIcon, StopIcon, UndoIcon } from './icons';
import { theme } from '../lib/theme';
import { badgeStyle } from '../lib/badgeStyle';
import { taskCheckSignal } from '../lib/task-check-signal';
import { handleDragReorder } from '../lib/dragReorder';
import { getTaskDockerBadgeLabel } from '../lib/docker';
import { displayTaskNameFromPrompt, shouldUsePromptDerivedTaskName } from '../lib/clean-task-name';
import type { Task } from '../store/types';
import { isLandedTaskState } from '../store/landing';
import {
  bringTaskToFront,
  getTaskSnoozedUntil,
  isTaskBackgrounded,
  sendTaskToBack,
  snoozeTask,
} from '../store/background-tasks';

interface TaskTitleBarProps {
  task: Task;
  isActive: boolean;
  onClose: () => void;
  /** Opens the finish dialog: evidence, tour, then merge or push. */
  onFinish: () => void;
  pushing: boolean;
  pushSuccess: boolean;
  onTitleEditRef: (h: EditableTextHandle) => void;
}

export function TaskTitleBar(props: TaskTitleBarProps) {
  const canStopAgents = () =>
    !props.task.coordinatorMode && !props.task.delegationParent && !props.task.coordinatedBy;
  const snoozeChoices = (keepRunning: boolean) =>
    (keepRunning ? [0.25, 0.5, 1, 2, 4, 8] : [1, 4, 8, 24, 72, 168]).map((hours) => ({
      label:
        hours < 1
          ? `${hours * 60} minutes`
          : hours === 1
            ? '1 hour'
            : hours === 168
              ? '1 week'
              : hours >= 24
                ? `${hours / 24} ${hours === 24 ? 'day' : 'days'}`
                : `${hours} hours`,
      icon: <ClockIcon size={14} />,
      run: () => void snoozeTask(props.task.id, hours, keepRunning),
    }));
  const snoozedUntil = () => getTaskSnoozedUntil(props.task.id);
  const dockerBadgeLabel = () => getTaskDockerBadgeLabel(props.task.dockerSource);
  const isLandedTask = () => isLandedTaskState(props.task.landingState);
  const landingBadge = () => {
    switch (props.task.landingState) {
      case 'landed_pending_review':
        return { label: 'Landed', color: theme.success, title: 'Landed — pending review' };
      case 'landed_cleanup_failed':
        return {
          label: 'Cleanup failed',
          color: theme.warning,
          title: props.task.landingReason ?? 'Landed, but cleanup failed',
        };
      case 'landing_escalated':
        return {
          label: 'Landing blocked',
          color: theme.warning,
          title: props.task.landingReason ?? 'Landing needs attention',
        };
      case 'landing_failed':
        return {
          label: 'Landing failed',
          color: theme.error,
          title: props.task.landingReason ?? 'Landing failed',
        };
      case 'reviewed':
        return { label: 'Reviewed', color: theme.fgMuted, title: 'Landing reviewed' };
      default:
        return null;
    }
  };
  // Hidden while the agent works: the result is about to change anyway. A busy
  // shell (dev server, watcher) is not agent work and must not hide a failure.
  const checkSignal = () => {
    const attention = getTaskAttentionState(props.task.id);
    if (attention === 'active' || (!attention && getTaskDotStatus(props.task.id) === 'busy'))
      return undefined;
    const git = store.taskGitStatus[props.task.id];
    return taskCheckSignal({
      evidence: getEvidenceConfidence(props.task, git),
      evidencePackage: props.task.evidence,
      verificationRun: props.task.verificationRun,
      verification: props.task.verification,
      verifyCommandConfigured: Boolean(getVerifyCommand(props.task.id)),
      headSha: git?.head_sha,
    });
  };
  const titleLabel = () => {
    const initialPrompt = props.task.savedInitialPrompt?.trim();
    if (
      !initialPrompt ||
      !shouldUsePromptDerivedTaskName(
        props.task.name,
        initialPrompt,
        props.task.nameIsAutoGenerated,
      )
    ) {
      return props.task.name;
    }
    return displayTaskNameFromPrompt(initialPrompt) || props.task.name;
  };
  const finishTitle = () => {
    const base = props.task.baseBranch ?? 'base';
    return props.pushing ? 'Pushing… (open to see output)' : `Finish: merge into ${base} or push`;
  };

  const statusDescription = () =>
    getDotTooltip(getTaskDotStatus(props.task.id), getTaskAttentionState(props.task.id));

  function handleTitleMouseDown(e: MouseEvent) {
    handleDragReorder(e, {
      itemId: props.task.id,
      getTaskOrder: () => store.taskOrder,
      onReorder: reorderTask,
      onTap: () => activateTaskFromPointer(props.task.id),
    });
  }

  return (
    <div class="task-title-bar" data-active={props.isActive} onMouseDown={handleTitleMouseDown}>
      <EditableText
        value={titleLabel()}
        onCommit={(v) => updateTaskName(props.task.id, v)}
        class="editable-text"
        title={props.task.savedInitialPrompt || titleLabel()}
        ref={(h) => props.onTitleEditRef(h)}
      />
      <div class="task-title-details">
        <span class="task-title-status" title={statusDescription()}>
          <StatusDot
            status={getTaskDotStatus(props.task.id)}
            taskId={props.task.id}
            size="md"
            attention={getTaskAttentionState(props.task.id)}
          />
          <span>
            <span>{statusDescription().split(' — ')[0]}</span>
            <span class="task-status-explanation">
              {statusDescription().includes(' — ')
                ? ` — ${statusDescription().split(' — ').slice(1).join(' — ')}`
                : ''}
            </span>
            <Show when={checkSignal()}>
              {(signal) => (
                <span style={{ color: signal().color }} title={signal().title}>
                  {` · ${signal().label}`}
                </span>
              )}
            </Show>
          </span>
        </span>
        <Show when={props.task.gitIsolation === 'direct'}>
          <span style={badgeStyle(theme.warning)}>{props.task.branchName}</span>
        </Show>
        <Show when={props.task.gitIsolation === 'none'}>
          <span style={badgeStyle(theme.fgMuted)}>no git</span>
        </Show>
        <Show when={props.task.dockerMode}>
          <span style={badgeStyle(theme.fgMuted)} title={props.task.dockerImage}>
            {dockerBadgeLabel()}
          </span>
        </Show>
        <Show when={props.task.externalWorktree}>
          <span style={badgeStyle(theme.accent)}>Imported</span>
        </Show>
        <Show when={isTaskBackgrounded(props.task.id)}>
          <span style={badgeStyle(theme.fgMuted)}>
            {snoozedUntil() === undefined
              ? 'Background'
              : `Snoozed until ${new Date(snoozedUntil() ?? 0).toLocaleString([], { weekday: 'short', hour: '2-digit', minute: '2-digit' })}`}
          </span>
        </Show>
        <Show when={props.task.needsReview}>
          <span
            style={badgeStyle(theme.warning)}
            title={props.task.landingReason ?? 'Review this task'}
          >
            Review
          </span>
        </Show>
        <Show when={landingBadge()}>
          {(badge) => (
            <button
              style={{
                ...badgeStyle(badge().color),
                cursor: props.task.landingState === 'landed_pending_review' ? 'pointer' : 'default',
              }}
              title={
                props.task.landingState === 'landed_pending_review'
                  ? `${badge().title}. Click to mark reviewed.`
                  : badge().title
              }
              onClick={(e) => {
                e.stopPropagation();
                if (props.task.landingState === 'landed_pending_review') {
                  clearTaskLandingReview(props.task.id);
                }
              }}
            >
              {badge().label}
            </button>
          )}
        </Show>
      </div>
      <div class="task-title-actions">
        <div class="task-action-group" role="group" aria-label="Task actions">
          <Show when={props.task.gitIsolation === 'worktree' && !isLandedTask()}>
            <button
              type="button"
              class="task-finish-btn"
              data-state={props.pushing ? 'pushing' : props.pushSuccess ? 'pushed' : undefined}
              title={finishTitle()}
              onClick={(e) => {
                e.stopPropagation();
                props.onFinish();
              }}
            >
              <Show
                when={!props.pushing}
                fallback={
                  <span
                    class="inline-spinner"
                    aria-hidden="true"
                    style={{ width: '12px', height: '12px' }}
                  />
                }
              >
                <svg width="14" height="14" viewBox="0 0 16 16" fill="currentColor">
                  <path d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8Zm1.5 0a6.5 6.5 0 1 0 13 0 6.5 6.5 0 0 0-13 0Zm10.28-1.72-4.5 4.5a.75.75 0 0 1-1.06 0l-2-2a.75.75 0 0 1 1.06-1.06L6.75 9.19l3.97-3.97a.75.75 0 0 1 1.06 1.06Z" />
                </svg>
              </Show>
              {props.pushing ? 'Pushing…' : props.pushSuccess ? 'Pushed' : 'Finish'}
            </button>
          </Show>
          <MoreMenu
            label="Later"
            icon={<ClockIcon size={14} />}
            class="task-finish-btn"
            items={[
              {
                label: isTaskBackgrounded(props.task.id)
                  ? 'Restore to front'
                  : 'Snooze until new activity',
                icon: isTaskBackgrounded(props.task.id) ? (
                  <UndoIcon size={14} />
                ) : (
                  <ActivityIcon size={14} />
                ),
                run: () =>
                  isTaskBackgrounded(props.task.id)
                    ? bringTaskToFront(props.task.id)
                    : sendTaskToBack(props.task.id),
              },
              {
                label: 'Snooze · keep running',
                icon: <PlayIcon size={14} />,
                children: snoozeChoices(true),
              },
              {
                label: 'Snooze · stop agents',
                icon: <StopIcon size={14} />,
                children: snoozeChoices(false),
                disabled: !canStopAgents(),
                title: canStopAgents()
                  ? undefined
                  : 'Coordinated tasks need to keep their agents running.',
              },
              ...(canStopAgents()
                ? [
                    {
                      label: 'Minimize (stop agents)',
                      icon: (
                        <svg
                          width="14"
                          height="14"
                          viewBox="0 0 16 16"
                          fill="currentColor"
                          aria-hidden="true"
                        >
                          <path d="M2 8a.75.75 0 0 1 .75-.75h10.5a.75.75 0 0 1 0 1.5H2.75A.75.75 0 0 1 2 8Z" />
                        </svg>
                      ),
                      run: () => void collapseTask(props.task.id),
                    },
                  ]
                : []),
            ]}
          />
        </div>
        <div class="task-action-group" role="group" aria-label="View actions">
          <IconButton
            icon={
              <svg
                width="16"
                height="16"
                viewBox="0 0 16 16"
                fill="none"
                stroke="currentColor"
                stroke-width="1.5"
              >
                <rect x="1.75" y="2.75" width="12.5" height="10.5" rx="1.5" />
                <path d="M10 2.75v10.5" />
              </svg>
            }
            onClick={() =>
              isTaskCanvasVisible(props.task)
                ? closeTaskCanvas(props.task.id)
                : openTaskCanvas(props.task.id)
            }
            title={isTaskCanvasVisible(props.task) ? 'Close canvas' : 'Open canvas'}
            pressed={isTaskCanvasVisible(props.task)}
          />
          <IconButton
            icon={
              <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor">
                <path d="M2.75 5.5A.75.75 0 0 0 3.5 4.75V3.5h1.25a.75.75 0 0 0 0-1.5H2.5a.5.5 0 0 0-.5.5v2.25c0 .414.336.75.75.75ZM12.5 4.75a.75.75 0 0 0 1.5 0V2.5a.5.5 0 0 0-.5-.5h-2.25a.75.75 0 0 0 0 1.5h1.25v1.25ZM3.5 11.25a.75.75 0 0 0-1.5 0V13.5a.5.5 0 0 0 .5.5h2.25a.75.75 0 0 0 0-1.5H3.5v-1.25ZM13.25 10.5a.75.75 0 0 0-.75.75v1.25h-1.25a.75.75 0 0 0 0 1.5H13.5a.5.5 0 0 0 .5-.5v-2.25a.75.75 0 0 0-.75-.75Z" />
              </svg>
            }
            onClick={() => {
              toggleTaskFocusMode(props.task.id);
            }}
            title={store.focusMode ? 'Exit focus mode' : 'Focus on this task'}
            pressed={store.focusMode}
          />
        </div>
        <div class="task-action-group" role="group" aria-label="Close task">
          <IconButton icon={<CloseIcon />} onClick={() => props.onClose()} title="Close task" />
        </div>
      </div>
    </div>
  );
}
