package com.parallelcode.phone

// GENERATED FILE - DO NOT EDIT.
//
// Regenerate with: node scripts/generate-android-looks.mjs
// Source of truth: src/lib/look.ts (ids, labels, descriptions, tone) and
// src/styles.css (colors and radii), matching the desktop app.
//
// The desktop themes set only the variables they change and inherit the rest
// from :root; every palette below is that cascade fully resolved, so the phone
// has no fallbacks of its own. Gradients are flattened to their middle stop
// because the phone draws flat surfaces; everything else is the exact value.

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

/**
 * One desktop look preset: every color and radius the phone draws with.
 *
 * Read these through [LookPresets] rather than constructing one.
 */
@Immutable
data class LookPalette(
    val id: String,
    val label: String,
    val description: String,
    /** True for the desktop's light presets. */
    val dark: Boolean,
    // Surfaces and state, from the desktop's --bg family.
    val bg: Color,
    val bgElevated: Color,
    val bgInput: Color,
    val bgHover: Color,
    val bgSelected: Color,
    // Borders.
    val border: Color,
    val borderSubtle: Color,
    val borderFocus: Color,
    // Text.
    val fg: Color,
    val fgMuted: Color,
    val fgSubtle: Color,
    // Accent family.
    val accent: Color,
    val accentHover: Color,
    val accentText: Color,
    val link: Color,
    // Status hues: success, error and warning plus the secondary
    // review and info hues the desktop keeps off the accent.
    val success: Color,
    val error: Color,
    val warning: Color,
    val review: Color,
    val info: Color,
    // Panels.
    val islandBg: Color,
    val islandBorder: Color,
    val containerBg: Color,
    val panelBg: Color,
    // Diff line tints.
    val diffAddBg: Color,
    val diffRemoveBg: Color,
    // The desktop's corner radius scale, in dp.
    val radiusXs: Dp,
    val radiusSm: Dp,
    val radiusMd: Dp,
    val radiusLg: Dp,
    /** Corner radius of an island or card, `--island-radius`. */
    val radiusIsland: Dp,
    /**
     * Id of the [TERMINAL_THEMES] entry this look draws terminals with, so agent
     * output follows the look the way it does on the desktop.
     */
    val terminalThemeId: String,
)

/**
 * One of the desktop's terminal color sets: a default text color and the 16 ANSI
 * colors, in the order `ansi[c]` is indexed in TerminalStyle.kt.
 */
@Immutable
data class TerminalTheme(
    val id: String,
    val foreground: Int,
    val ansi: List<Int>,
)

private val TerminalLight =
    TerminalTheme(
        id = "light",
        foreground = -14736599,
        ansi =
            listOf(
                -14407378,
                -3202514,
                -15637719,
                -7705344,
                -16428882,
                -8236833,
                -14975869,
                -9537663,
                -11050902,
                -6025690,
                -15040713,
                -10273791,
                -16160294,
                -10077766,
                -13528406,
                -14736599,
            ),
    )

private val TerminalObsidian =
    TerminalTheme(
        id = "obsidian",
        foreground = -1776412,
        ansi =
            listOf(
                -13750738,
                -2061162,
                -6764114,
                -2113138,
                -7359524,
                -4083480,
                -7419447,
                -3552823,
                -8026747,
                -1400662,
                -5382975,
                -1387608,
                -5716504,
                -2964240,
                -5842214,
                -1184275,
            ),
    )

private val TerminalNoir =
    TerminalTheme(
        id = "noir",
        foreground = -1513233,
        ansi =
            listOf(
                -12895672,
                -1011830,
                -6764114,
                -2114941,
                -7356963,
                -1858602,
                -7548976,
                -3882032,
                -7303010,
                -677724,
                -5382975,
                -1388379,
                -5648918,
                -1131035,
                -5841700,
                -855305,
            ),
    )

private val TerminalIslandsDark =
    TerminalTheme(
        id = "islands-dark",
        foreground = -4407612,
        ansi =
            listOf(
                -13618118,
                -568220,
                -9786509,
                -1531074,
                -9593352,
                -4351256,
                -9389625,
                -4407612,
                -7697004,
                -34683,
                -7879282,
                -737687,
                -7161857,
                -3034637,
                -7220516,
                -1117964,
            ),
    )

/** Every terminal theme, by id. */
val ALL_TERMINAL_THEMES: Map<String, TerminalTheme> =
    listOf(
        TerminalLight,
        TerminalObsidian,
        TerminalNoir,
        TerminalIslandsDark,
    ).associateBy { it.id }

private val Noir =
    LookPalette(
        id = "noir",
        label = "Noir",
        description = "Ink-dark surfaces, soft lilac, and quiet controls that follow your focus",
        dark = true,
        bg = Color(0xFF0C0C10),
        bgElevated = Color(0xFF1C1C24),
        bgInput = Color(0xFF202029),
        bgHover = Color(0xFF2A2935),
        bgSelected = Color(0xFF343043),
        border = Color(0xFF33323E),
        borderSubtle = Color(0xFF25252E),
        borderFocus = Color(0xFFB7A5F5),
        fg = Color(0xFFE8E8EF),
        fgMuted = Color(0xFFB1B0BF),
        fgSubtle = Color(0xFF9392A3),
        accent = Color(0xFFB7A5F5),
        accentHover = Color(0xFFCBBCFB),
        accentText = Color(0xFF191421),
        link = Color(0xFF9CC8EA),
        success = Color(0xFF98C9AE),
        error = Color(0xFFF08F8A),
        warning = Color(0xFFDFBA83),
        review = Color(0xFF8FBDDD),
        info = Color(0xFFC4C3D0),
        islandBg = Color(0xFF15151B),
        islandBorder = Color(0xFF33323E),
        containerBg = Color(0xFF15151B),
        panelBg = Color(0xFF15151B),
        diffAddBg = Color(0x2698C9AE),
        diffRemoveBg = Color(0x26F08F8A),
        radiusXs = 4.dp,
        radiusSm = 6.dp,
        radiusMd = 10.dp,
        radiusLg = 12.dp,
        radiusIsland = 12.dp,
        terminalThemeId = "noir",
    )

private val Obsidian =
    LookPalette(
        id = "obsidian",
        label = "Obsidian",
        description = "Neutral charcoal surfaces, warm amber accent, and clean typography",
        dark = true,
        bg = Color(0xFF171717),
        bgElevated = Color(0xFF242424),
        bgInput = Color(0xFF262626),
        bgHover = Color(0xFF303030),
        bgSelected = Color(0xFF353535),
        border = Color(0xFF333333),
        borderSubtle = Color(0xFF292929),
        borderFocus = Color(0xFFC4A77D),
        fg = Color(0xFFEDEDED),
        fgMuted = Color(0xFFB5B5B5),
        fgSubtle = Color(0xFF919191),
        accent = Color(0xFFC4A77D),
        accentHover = Color(0xFFD6BD96),
        accentText = Color(0xFF1E1B16),
        link = Color(0xFFD6BD96),
        success = Color(0xFF98C9AE),
        error = Color(0xFFEAA0AA),
        warning = Color(0xFFF29B70),
        review = Color(0xFFC1B0E8),
        info = Color(0xFFC9C9C9),
        islandBg = Color(0xFF1E1E1E),
        islandBorder = Color(0xFF303030),
        containerBg = Color(0xFF1E1E1E),
        panelBg = Color(0xFF1E1E1E),
        diffAddBg = Color(0x1F98C9AE),
        diffRemoveBg = Color(0x1FEAA0AA),
        radiusXs = 4.dp,
        radiusSm = 4.dp,
        radiusMd = 0.dp,
        radiusLg = 0.dp,
        radiusIsland = 0.dp,
        terminalThemeId = "obsidian",
    )

private val ObsidianLight =
    LookPalette(
        id = "obsidian-light",
        label = "Obsidian Light",
        description = "Obsidian on warm paper neutrals with a bronze accent",
        dark = false,
        bg = Color(0xFFF4F4F2),
        bgElevated = Color(0xFFFFFFFF),
        bgInput = Color(0xFFF2F2F0),
        bgHover = Color(0xFFEBEBE8),
        bgSelected = Color(0xFFE2E1DC),
        border = Color(0xFFDDDCD8),
        borderSubtle = Color(0xFFE9E8E4),
        borderFocus = Color(0xFF8A6433),
        fg = Color(0xFF1F1F1F),
        fgMuted = Color(0xFF555555),
        fgSubtle = Color(0xFF6E6E6E),
        accent = Color(0xFF8A6433),
        accentHover = Color(0xFF75532A),
        accentText = Color(0xFFFFFFFF),
        link = Color(0xFF75532A),
        success = Color(0xFF2F7D4F),
        error = Color(0xFFB3383F),
        warning = Color(0xFFAD4E00),
        review = Color(0xFF6D4FC2),
        info = Color(0xFF5E5E5E),
        islandBg = Color(0xFFFFFFFF),
        islandBorder = Color(0xFFDDDCD8),
        containerBg = Color(0xFFFFFFFF),
        panelBg = Color(0xFFFFFFFF),
        diffAddBg = Color(0x1F2F7D4F),
        diffRemoveBg = Color(0x1AB3383F),
        radiusXs = 0.dp,
        radiusSm = 0.dp,
        radiusMd = 0.dp,
        radiusLg = 0.dp,
        radiusIsland = 0.dp,
        terminalThemeId = "light",
    )

private val IslandsDark =
    LookPalette(
        id = "islands-dark",
        label = "Islands Dark",
        description = "JetBrains-inspired dark panels on a tinted frame",
        dark = true,
        bg = Color(0xFF2B323D),
        bgElevated = Color(0xFF181A1D),
        bgInput = Color(0xFF1E2126),
        bgHover = Color(0xFF23262C),
        bgSelected = Color(0xFF25324D),
        border = Color(0xFF2C2F34),
        borderSubtle = Color(0xFF232529),
        borderFocus = Color(0xFF286CF5),
        fg = Color(0xFFBCBEC4),
        fgMuted = Color(0xFF9A9DA4),
        fgSubtle = Color(0xFF7A7E85),
        accent = Color(0xFF286CF5),
        accentHover = Color(0xFF6D9DF8),
        accentText = Color(0xFFFFFFFF),
        link = Color(0xFF6D9DF8),
        success = Color(0xFF6AAB73),
        error = Color(0xFFF75464),
        warning = Color(0xFFE8A33E),
        review = Color(0xFFC084FC),
        info = Color(0xFF60A5FA),
        islandBg = Color(0xFF181A1D),
        islandBorder = Color(0xFF2C2F34),
        containerBg = Color(0xFF181A1D),
        panelBg = Color(0xFF181A1D),
        diffAddBg = Color(0x1A2FD198),
        diffRemoveBg = Color(0x1AFF5F73),
        radiusXs = 4.dp,
        radiusSm = 6.dp,
        radiusMd = 8.dp,
        radiusLg = 12.dp,
        radiusIsland = 12.dp,
        terminalThemeId = "islands-dark",
    )

private val IslandsLight =
    LookPalette(
        id = "islands-light",
        label = "Islands Light",
        description = "JetBrains-inspired light panels on a soft tinted frame",
        dark = false,
        bg = Color(0xFFCDD6E4),
        bgElevated = Color(0xFFFFFFFF),
        bgInput = Color(0xFFF3F4F6),
        bgHover = Color(0xFFE8EAEF),
        bgSelected = Color(0xFFCFE1FF),
        border = Color(0xFFD3D5DB),
        borderSubtle = Color(0xFFE3E5EA),
        borderFocus = Color(0xFF2C6DEF),
        fg = Color(0xFF1F2329),
        fgMuted = Color(0xFF5E6066),
        fgSubtle = Color(0xFF8D9199),
        accent = Color(0xFF2C6DEF),
        accentHover = Color(0xFF5A8DFF),
        accentText = Color(0xFFFFFFFF),
        link = Color(0xFF2C6DEF),
        success = Color(0xFF369650),
        error = Color(0xFFD62B40),
        warning = Color(0xFFA98708),
        review = Color(0xFF7C3AED),
        info = Color(0xFF1D6FD6),
        islandBg = Color(0xFFFFFFFF),
        islandBorder = Color(0xFFD3D5DB),
        containerBg = Color(0xFFFFFFFF),
        panelBg = Color(0xFFFFFFFF),
        diffAddBg = Color(0x24369650),
        diffRemoveBg = Color(0x1FD62B40),
        radiusXs = 4.dp,
        radiusSm = 6.dp,
        radiusMd = 8.dp,
        radiusLg = 12.dp,
        radiusIsland = 12.dp,
        terminalThemeId = "light",
    )

private val Minimal =
    LookPalette(
        id = "minimal",
        label = "Minimal",
        description = "Flat monochrome with warm off-white accent",
        dark = true,
        bg = Color(0xFF191916),
        bgElevated = Color(0xFF1E1E1B),
        bgInput = Color(0xFF252520),
        bgHover = Color(0x12FFFFFF),
        bgSelected = Color(0x38C8BFA0),
        border = Color(0xFF333230),
        borderSubtle = Color(0xFF2A2925),
        borderFocus = Color(0xFFE8DEC5),
        fg = Color(0xFFECECEC),
        fgMuted = Color(0xFFC0C0C0),
        fgSubtle = Color(0xFF999999),
        accent = Color(0xFFC8BFA0),
        accentHover = Color(0xFFE6DEC5),
        accentText = Color(0xFF090909),
        link = Color(0xFFE6DEC5),
        success = Color(0xFF8AAA7A),
        error = Color(0xFFD05656),
        warning = Color(0xFFD4AA58),
        review = Color(0xFFC084FC),
        info = Color(0xFF60A5FA),
        islandBg = Color(0xFF1B1B18),
        islandBorder = Color(0xFF2A2925),
        containerBg = Color(0xFF21211D),
        panelBg = Color(0xFF252520),
        diffAddBg = Color(0x1A2FD198),
        diffRemoveBg = Color(0x1AFF5F73),
        radiusXs = 4.dp,
        radiusSm = 6.dp,
        radiusMd = 8.dp,
        radiusLg = 12.dp,
        radiusIsland = 10.dp,
        terminalThemeId = "noir",
    )

private val Graphite =
    LookPalette(
        id = "graphite",
        label = "Graphite",
        description = "Cool neon blue with subtle glow",
        dark = true,
        bg = Color(0xFF141C26),
        bgElevated = Color(0xFF1C2630),
        bgInput = Color(0xFF19232E),
        bgHover = Color(0xFF253240),
        bgSelected = Color(0xFF1C3E55),
        border = Color(0xFF2E3E50),
        borderSubtle = Color(0xFF222E3A),
        borderFocus = Color(0xFF2EC8FF),
        fg = Color(0xFFD7E4F0),
        fgMuted = Color(0xFF9BB0C3),
        fgSubtle = Color(0xFF678197),
        accent = Color(0xFF2EC8FF),
        accentHover = Color(0xFF59D7FF),
        accentText = Color(0xFF031018),
        link = Color(0xFF73DFFF),
        success = Color(0xFF2FD198),
        error = Color(0xFFFF5F73),
        warning = Color(0xFFFFC569),
        review = Color(0xFFC084FC),
        info = Color(0xFF60A5FA),
        islandBg = Color(0xFF192028),
        islandBorder = Color(0xFF2E3E50),
        containerBg = Color(0xFF161E28),
        panelBg = Color(0xFF1C2630),
        diffAddBg = Color(0x1A2FD198),
        diffRemoveBg = Color(0x1AFF5F73),
        radiusXs = 4.dp,
        radiusSm = 6.dp,
        radiusMd = 8.dp,
        radiusLg = 12.dp,
        radiusIsland = 12.dp,
        terminalThemeId = "noir",
    )

private val Midnight =
    LookPalette(
        id = "midnight",
        label = "Midnight",
        description = "Graphite with pure black terminals",
        dark = true,
        bg = Color(0xFF141C26),
        bgElevated = Color(0xFF1C2630),
        bgInput = Color(0xFF19232E),
        bgHover = Color(0xFF253240),
        bgSelected = Color(0xFF1C3E55),
        border = Color(0xFF2E3E50),
        borderSubtle = Color(0xFF222E3A),
        borderFocus = Color(0xFF2EC8FF),
        fg = Color(0xFFD7E4F0),
        fgMuted = Color(0xFF9BB0C3),
        fgSubtle = Color(0xFF678197),
        accent = Color(0xFF2EC8FF),
        accentHover = Color(0xFF59D7FF),
        accentText = Color(0xFF031018),
        link = Color(0xFF73DFFF),
        success = Color(0xFF2FD198),
        error = Color(0xFFFF5F73),
        warning = Color(0xFFFFC569),
        review = Color(0xFFC084FC),
        info = Color(0xFF60A5FA),
        islandBg = Color(0xFF192028),
        islandBorder = Color(0xFF2E3E50),
        containerBg = Color(0xFF161E28),
        panelBg = Color(0xFF000000),
        diffAddBg = Color(0x1A2FD198),
        diffRemoveBg = Color(0x1AFF5F73),
        radiusXs = 4.dp,
        radiusSm = 6.dp,
        radiusMd = 8.dp,
        radiusLg = 12.dp,
        radiusIsland = 12.dp,
        terminalThemeId = "noir",
    )

private val Classic =
    LookPalette(
        id = "classic",
        label = "Classic",
        description = "Original dark utilitarian look",
        dark = true,
        bg = Color(0xFF161618),
        bgElevated = Color(0xFF2D2E32),
        bgInput = Color(0xFF2D2E32),
        bgHover = Color(0xFF3A3C40),
        bgSelected = Color(0xFF3E508A),
        border = Color(0xFF393B3F),
        borderSubtle = Color(0xFF2D2E32),
        borderFocus = Color(0xFF4267FF),
        fg = Color(0xFFCCCDD2),
        fgMuted = Color(0xFF8B8D93),
        fgSubtle = Color(0xFF767980),
        accent = Color(0xFF4267FF),
        accentHover = Color(0xFF3A5BFF),
        accentText = Color(0xFFFFFFFF),
        link = Color(0xFF6F8EFF),
        success = Color(0xFF0DBC79),
        error = Color(0xFFF75464),
        warning = Color(0xFFF2C55C),
        review = Color(0xFFC084FC),
        info = Color(0xFF60A5FA),
        islandBg = Color(0xFF242428),
        islandBorder = Color(0xFF393B3F),
        containerBg = Color(0xFF242428),
        panelBg = Color(0xFF2D2E32),
        diffAddBg = Color(0x1A2FD198),
        diffRemoveBg = Color(0x1AFF5F73),
        radiusXs = 4.dp,
        radiusSm = 6.dp,
        radiusMd = 8.dp,
        radiusLg = 12.dp,
        radiusIsland = 10.dp,
        terminalThemeId = "noir",
    )

private val Indigo =
    LookPalette(
        id = "indigo",
        label = "Indigo",
        description = "Deep indigo base with electric violet accents",
        dark = true,
        bg = Color(0xFF171C30),
        bgElevated = Color(0xFF1C2038),
        bgInput = Color(0xFF1A1E35),
        bgHover = Color(0xFF262E50),
        bgSelected = Color(0xFF2E3265),
        border = Color(0xFF384270),
        borderSubtle = Color(0xFF2B3456),
        borderFocus = Color(0xFF7A78FF),
        fg = Color(0xFFDEDDFF),
        fgMuted = Color(0xFFB1B2DE),
        fgSubtle = Color(0xFF8286B6),
        accent = Color(0xFF7A78FF),
        accentHover = Color(0xFF938FFF),
        accentText = Color(0xFF090A18),
        link = Color(0xFFA8A6FF),
        success = Color(0xFF48D2A2),
        error = Color(0xFFFF6C90),
        warning = Color(0xFFFFCF7A),
        review = Color(0xFFC084FC),
        info = Color(0xFF60A5FA),
        islandBg = Color(0xFF1A1E35),
        islandBorder = Color(0xFF384270),
        containerBg = Color(0xFF151822),
        panelBg = Color(0xFF1C2038),
        diffAddBg = Color(0x1A2FD198),
        diffRemoveBg = Color(0x1AFF5F73),
        radiusXs = 4.dp,
        radiusSm = 6.dp,
        radiusMd = 8.dp,
        radiusLg = 12.dp,
        radiusIsland = 12.dp,
        terminalThemeId = "noir",
    )

private val Ember =
    LookPalette(
        id = "ember",
        label = "Ember",
        description = "Warm copper highlights and contrast",
        dark = true,
        bg = Color(0xFF171416),
        bgElevated = Color(0xFF211918),
        bgInput = Color(0xFF1D1614),
        bgHover = Color(0xFF31211D),
        bgSelected = Color(0xFF552D1E),
        border = Color(0xFF4E3831),
        borderSubtle = Color(0xFF322420),
        borderFocus = Color(0xFFFF944D),
        fg = Color(0xFFF2DDD1),
        fgMuted = Color(0xFFD5AB94),
        fgSubtle = Color(0xFF9F7561),
        accent = Color(0xFFFF944D),
        accentHover = Color(0xFFFFAC73),
        accentText = Color(0xFF201006),
        link = Color(0xFFFFB47F),
        success = Color(0xFF33C791),
        error = Color(0xFFFF6A7F),
        warning = Color(0xFFFFD27A),
        review = Color(0xFFC084FC),
        info = Color(0xFF60A5FA),
        islandBg = Color(0xFF1E1514),
        islandBorder = Color(0xFF4E3831),
        containerBg = Color(0xFF1A1212),
        panelBg = Color(0xFF211918),
        diffAddBg = Color(0x1A2FD198),
        diffRemoveBg = Color(0x1AFF5F73),
        radiusXs = 4.dp,
        radiusSm = 6.dp,
        radiusMd = 8.dp,
        radiusLg = 12.dp,
        radiusIsland = 12.dp,
        terminalThemeId = "noir",
    )

private val Glacier =
    LookPalette(
        id = "glacier",
        label = "Glacier",
        description = "Clean teal accents with softer depth",
        dark = true,
        bg = Color(0xFF1D2932),
        bgElevated = Color(0xFF232E3A),
        bgInput = Color(0xFF202A34),
        bgHover = Color(0xFF2F4050),
        bgSelected = Color(0xFF28535D),
        border = Color(0xFF3B5363),
        borderSubtle = Color(0xFF2E424F),
        borderFocus = Color(0xFF50E2D3),
        fg = Color(0xFFE5EFF5),
        fgMuted = Color(0xFFBED2DC),
        fgSubtle = Color(0xFF92AEBB),
        accent = Color(0xFF50E2D3),
        accentHover = Color(0xFF76ECE0),
        accentText = Color(0xFF041413),
        link = Color(0xFF8CF2E8),
        success = Color(0xFF4ED59F),
        error = Color(0xFFFF6F88),
        warning = Color(0xFFFFD57D),
        review = Color(0xFFC084FC),
        info = Color(0xFF60A5FA),
        islandBg = Color(0xFF212B36),
        islandBorder = Color(0xFF3B5363),
        containerBg = Color(0xFF1C2730),
        panelBg = Color(0xFF232E3A),
        diffAddBg = Color(0x1A2FD198),
        diffRemoveBg = Color(0x1AFF5F73),
        radiusXs = 4.dp,
        radiusSm = 6.dp,
        radiusMd = 8.dp,
        radiusLg = 12.dp,
        radiusIsland = 12.dp,
        terminalThemeId = "noir",
    )

private val Zenburnesque =
    LookPalette(
        id = "zenburnesque",
        label = "Zenburnesque",
        description = "Warm sage and muted earth tones",
        dark = true,
        bg = Color(0xFF232220),
        bgElevated = Color(0xFF2E2D2A),
        bgInput = Color(0xFF2A2927),
        bgHover = Color(0xFF3A3936),
        bgSelected = Color(0xFF3F2E30),
        border = Color(0xFF484640),
        borderSubtle = Color(0xFF383634),
        borderFocus = Color(0xFFCC9393),
        fg = Color(0xFFDCDCCC),
        fgMuted = Color(0xFFA0A090),
        fgSubtle = Color(0xFF7F8F7F),
        accent = Color(0xFFCC9393),
        accentHover = Color(0xFFD8A8A8),
        accentText = Color(0xFF1A0E0E),
        link = Color(0xFFD8A8A8),
        success = Color(0xFF7F9F7F),
        error = Color(0xFFE37170),
        warning = Color(0xFFF0DFAF),
        review = Color(0xFFC084FC),
        info = Color(0xFF60A5FA),
        islandBg = Color(0xFF262523),
        islandBorder = Color(0xFF484640),
        containerBg = Color(0xFF212120),
        panelBg = Color(0xFF2E2D2A),
        diffAddBg = Color(0x1A2FD198),
        diffRemoveBg = Color(0x1AFF5F73),
        radiusXs = 4.dp,
        radiusSm = 6.dp,
        radiusMd = 8.dp,
        radiusLg = 12.dp,
        radiusIsland = 12.dp,
        terminalThemeId = "noir",
    )

private val CatppuccinMocha =
    LookPalette(
        id = "catppuccin-mocha",
        label = "Catppuccin Mocha",
        description = "Pastel mauve accents on the cozy Catppuccin Mocha palette",
        dark = true,
        bg = Color(0xFF1A1A28),
        bgElevated = Color(0xFF1E1E2E),
        bgInput = Color(0xFF313244),
        bgHover = Color(0xFF45475A),
        bgSelected = Color(0xFF3B2F5A),
        border = Color(0xFF45475A),
        borderSubtle = Color(0xFF313244),
        borderFocus = Color(0xFFCBA6F7),
        fg = Color(0xFFCDD6F4),
        fgMuted = Color(0xFFA6ADC8),
        fgSubtle = Color(0xFF7F849C),
        accent = Color(0xFFCBA6F7),
        accentHover = Color(0xFFD6B8FA),
        accentText = Color(0xFF1E1E2E),
        link = Color(0xFF74C7EC),
        success = Color(0xFFA6E3A1),
        error = Color(0xFFF38BA8),
        warning = Color(0xFFF9E2AF),
        review = Color(0xFFC084FC),
        info = Color(0xFF60A5FA),
        islandBg = Color(0xFF1E1E2E),
        islandBorder = Color(0xFF45475A),
        containerBg = Color(0xFF181825),
        panelBg = Color(0xFF1E1E2E),
        diffAddBg = Color(0x1A2FD198),
        diffRemoveBg = Color(0x1AFF5F73),
        radiusXs = 4.dp,
        radiusSm = 6.dp,
        radiusMd = 8.dp,
        radiusLg = 12.dp,
        radiusIsland = 12.dp,
        terminalThemeId = "noir",
    )

private val Workbench =
    LookPalette(
        id = "workbench",
        label = "Workbench",
        description = "VS Code-inspired flat three-tier dark with cobalt blue",
        dark = true,
        bg = Color(0xFF181818),
        bgElevated = Color(0xFF1F1F1F),
        bgInput = Color(0xFF313131),
        bgHover = Color(0xFF2A2D2E),
        bgSelected = Color(0xFF04395E),
        border = Color(0xFF2B2B2B),
        borderSubtle = Color(0xFF1F1F1F),
        borderFocus = Color(0xFF0078D4),
        fg = Color(0xFFCCCCCC),
        fgMuted = Color(0xFF969696),
        fgSubtle = Color(0xFF6C6C6C),
        accent = Color(0xFF0078D4),
        accentHover = Color(0xFF1E90E0),
        accentText = Color(0xFFFFFFFF),
        link = Color(0xFF4DAAFC),
        success = Color(0xFF89D185),
        error = Color(0xFFF14C4C),
        warning = Color(0xFFCCA700),
        review = Color(0xFFC084FC),
        info = Color(0xFF60A5FA),
        islandBg = Color(0xFF252526),
        islandBorder = Color(0xFF2B2B2B),
        containerBg = Color(0xFF1F1F1F),
        panelBg = Color(0xFF1F1F1F),
        diffAddBg = Color(0x1A2FD198),
        diffRemoveBg = Color(0x1AFF5F73),
        radiusXs = 4.dp,
        radiusSm = 6.dp,
        radiusMd = 8.dp,
        radiusLg = 12.dp,
        radiusIsland = 0.dp,
        terminalThemeId = "noir",
    )

/** Every preset, in the order the desktop lists them. */
val ALL_LOOK_PALETTES: List<LookPalette> =
    listOf(
        Noir,
        Obsidian,
        ObsidianLight,
        IslandsDark,
        IslandsLight,
        Minimal,
        Graphite,
        Midnight,
        Classic,
        Indigo,
        Ember,
        Glacier,
        Zenburnesque,
        CatppuccinMocha,
        Workbench,
    )
